<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="174102" started-at="2019-09-29T11:34:34Z" finished-at="2019-09-29T11:37:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="174102" started-at="2019-09-29T11:34:34Z" finished-at="2019-09-29T11:37:28Z">
      <class name="com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes@30b8a058]" name="beforeMethod" is-config="true" duration-ms="65498" started-at="2019-09-29T11:34:34Z" finished-at="2019-09-29T11:35:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TestDownloadInvoice()[pri:1, instance:com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes@30b8a058]" name="TestDownloadInvoice" duration-ms="40560" started-at="2019-09-29T11:35:39Z" finished-at="2019-09-29T11:36:20Z">
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at com.alphasense.Testautomation.utility.Utils.takeScreenshot(Utils.java:98)
at com.alphasense.Testautomation.pages.PageMyAccount.searchClothes(PageMyAccount.java:428)
at com.alphasense.Testautomation.pages.PageMyAccount.shippingClothes(PageMyAccount.java:451)
at com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes.TestDownloadInvoice(Test_PageMyAccountOrderShipClothes.java:85)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestDownloadInvoice -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes@30b8a058]" name="afterMethod" is-config="true" duration-ms="3432" started-at="2019-09-29T11:36:20Z" finished-at="2019-09-29T11:36:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes@30b8a058]" name="beforeMethod" is-config="true" duration-ms="26355" started-at="2019-09-29T11:36:23Z" finished-at="2019-09-29T11:36:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TestShippingClothes()[pri:2, instance:com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes@30b8a058]" name="TestShippingClothes" duration-ms="35267" started-at="2019-09-29T11:36:50Z" finished-at="2019-09-29T11:37:25Z">
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at com.alphasense.Testautomation.utility.Utils.takeScreenshot(Utils.java:98)
at com.alphasense.Testautomation.pages.PageMyAccount.searchClothes(PageMyAccount.java:428)
at com.alphasense.Testautomation.pages.PageMyAccount.shippingClothes(PageMyAccount.java:451)
at com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes.TestShippingClothes(Test_PageMyAccountOrderShipClothes.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestShippingClothes -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes@30b8a058]" name="afterMethod" is-config="true" duration-ms="2798" started-at="2019-09-29T11:37:25Z" finished-at="2019-09-29T11:37:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.alphasense.Testautomation.tests.Test_PageMyAccountOrderShipClothes -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
